<template>
  <div class="canvas-workspace" @pointerdown="hideContextMenu">
    <div class="canvas-frame">
      <div class="ruler-corner">0,0</div><div class="top-ruler">Линейка X</div><div class="left-ruler">Y</div>
      <div ref="surfaceRef" class="canvas-surface" @wheel.prevent="onWheelZoom" @dragover.prevent @drop.prevent="onPaletteDrop">
        <svg class="editor-canvas" :viewBox="canvasViewBox" @pointermove="onPointerMove" @pointerdown="onCanvasPointerDown" @contextmenu.prevent.stop="onContextMenu">
          <defs>
            <pattern id="editor-grid" :width="settings.gridStep" :height="settings.gridStep" patternUnits="userSpaceOnUse"><path :d="`M ${settings.gridStep} 0 L 0 0 0 ${settings.gridStep}`" fill="none" stroke="#e5e7eb" stroke-width="0.55" /></pattern>
            <pattern id="editor-grid-major" :width="majorGridStep" :height="majorGridStep" patternUnits="userSpaceOnUse"><rect :width="majorGridStep" :height="majorGridStep" fill="url(#editor-grid)" /><path :d="`M ${majorGridStep} 0 L 0 0 0 ${majorGridStep}`" fill="none" stroke="#cbd5e1" stroke-width="0.75" /></pattern>
          </defs>
          <rect :x="viewOrigin.x" :y="viewOrigin.y" :width="viewBoxWidth" :height="viewBoxHeight" fill="#dedbe0" />
          <g class="iso-page-layer"><rect class="iso-page-fill" :x="pageRect.x" :y="pageRect.y" :width="pageRect.width" :height="pageRect.height" /><rect :x="pageRect.x" :y="pageRect.y" :width="pageRect.width" :height="pageRect.height" fill="url(#editor-grid-major)" /><rect class="iso-page-outline" :x="pageRect.x" :y="pageRect.y" :width="pageRect.width" :height="pageRect.height" /><text class="iso-page-label" :x="pageRect.x + 8" :y="pageRect.y + 16">{{ settings.pageFormat }} {{ settings.pageOrientation === 'landscape' ? 'альбомная' : 'книжная' }}</text></g>
          <g class="origin-layer"><line x1="-10" y1="0" x2="10" y2="0" class="origin-line" /><line x1="0" y1="-10" x2="0" y2="10" class="origin-line" /><circle cx="0" cy="0" r="1.2" class="origin-dot" /><text x="4" y="-4" class="origin-label">0,0</text></g>
          <g class="guide-layer"><line v-for="guide in verticalGuides" :key="guide.id" :x1="guide.position" :y1="viewOrigin.y" :x2="guide.position" :y2="viewOrigin.y + viewBoxHeight" class="user-guide-line" /><line v-for="guide in horizontalGuides" :key="guide.id" :x1="viewOrigin.x" :y1="guide.position" :x2="viewOrigin.x + viewBoxWidth" :y2="guide.position" class="user-guide-line" /></g>
          <g class="connection-layer"><line v-for="line in symbolAttachmentLines" :key="line.id" :x1="line.x1" :y1="line.y1" :x2="line.x2" :y2="line.y2" :stroke="line.color" class="electrical-connection" /></g>
          <g class="object-layer">
            <g v-for="primitive in primitiveObjects" :key="primitive.id" class="primitive-object" @pointerdown.stop="onPrimitivePointerDown($event, primitive.id)">
              <rect v-if="primitive.kind === 'rectangle'" :x="primitive.x" :y="primitive.y" :width="primitive.width" :height="primitive.height" :fill="primitive.fill" :stroke="primitive.stroke" :stroke-width="primitive.strokeWidth" />
              <ellipse v-else-if="primitive.kind === 'ellipse'" :cx="primitive.x + primitive.width / 2" :cy="primitive.y + primitive.height / 2" :rx="Math.abs(primitive.width / 2)" :ry="Math.abs(primitive.height / 2)" :fill="primitive.fill" :stroke="primitive.stroke" :stroke-width="primitive.strokeWidth" />
              <line v-else :x1="primitive.x" :y1="primitive.y" :x2="primitive.x + primitive.width" :y2="primitive.y + primitive.height" :stroke="primitive.stroke" :stroke-width="primitive.strokeWidth" />
            </g>
            <g v-for="busbar in busbars" :key="busbar.id" class="busbar-object" @pointerdown.stop="onBusbarPointerDown($event, busbar.id)"><rect class="busbar" :style="{ fill: voltageColorById(busbar.voltageClassId) }" :x="busbar.x" :y="busbar.y" :width="busbar.width" :height="busbar.height" rx="1" /></g>
            <g v-for="symbol in symbolObjects" :key="symbol.id" class="symbol-object" @pointerdown.stop="onSymbolPointerDown($event, symbol.id)">
              <line :x1="symbol.x + symbol.width / 2" :y1="symbol.y - 24" :x2="symbol.x + symbol.width / 2" :y2="symbol.y" :stroke="voltageColorById(symbol.voltageClassId)" class="symbol-line" />
              <rect :x="symbol.x" :y="symbol.y" :width="symbol.width" :height="symbol.height" fill="#ffffff" :stroke="voltageColorById(symbol.voltageClassId)" class="symbol-body" />
              <line :x1="symbol.x + 7" :y1="symbol.y + symbol.height / 2" :x2="symbol.x + symbol.width - 7" :y2="symbol.y + symbol.height / 2" :stroke="voltageColorById(symbol.voltageClassId)" class="symbol-line" />
              <line :x1="symbol.x + symbol.width / 2" :y1="symbol.y + symbol.height" :x2="symbol.x + symbol.width / 2" :y2="symbol.y + symbol.height + 24" :stroke="voltageColorById(symbol.voltageClassId)" class="symbol-line" />
              <circle :cx="symbol.x + symbol.width / 2" :cy="symbol.y - 24" r="3" class="symbol-terminal" /><circle :cx="symbol.x + symbol.width / 2" :cy="symbol.y + symbol.height + 24" r="3" class="symbol-terminal" /><text class="symbol-label" :x="symbol.x + symbol.width + 9" :y="symbol.y + symbol.height / 2">{{ symbol.label }}</text>
            </g>
            <circle v-for="slot in baySlots" :key="slot.id" class="bay-slot" :cx="slot.x" :cy="slot.y" r="5" />
            <text v-for="object in textObjects" :key="object.id" class="canvas-text" :x="object.anchor.x" :y="object.anchor.y" :font-size="object.fontSize" :fill="object.fill" :transform="`rotate(${object.rotationDeg} ${object.anchor.x} ${object.anchor.y})`" dominant-baseline="middle" text-anchor="middle" @pointerdown.stop="onTextPointerDown($event, object.id)">{{ object.text }}</text>
          </g>
          <g v-if="selectionOverlayRect" class="selection-handles-layer"><rect class="selection-outline" :x="selectionOverlayRect.x" :y="selectionOverlayRect.y" :width="selectionOverlayRect.width" :height="selectionOverlayRect.height" /><rect v-for="handle in selectionHandles" :key="handle.id" class="selection-handle" :x="handle.x - handleSize / 2" :y="handle.y - handleSize / 2" :width="handleSize" :height="handleSize" /></g>
          <rect v-if="marqueeRect" class="selection-marquee" :x="marqueeRect.x" :y="marqueeRect.y" :width="marqueeRect.width" :height="marqueeRect.height" />
          <g v-if="busbars.length === 0 && textObjects.length === 0 && primitiveObjects.length === 0 && symbolObjects.length === 0" class="empty-canvas-hint"><text x="0" y="-20" text-anchor="middle">Пустой лист</text><text x="0" y="10" text-anchor="middle" class="hint-small">Перетащите фигуру из панели слева или используйте ПКМ</text></g>
        </svg>
        <MiniToolbar v-if="miniToolbarPosition" :x="miniToolbarPosition.x" :y="miniToolbarPosition.y" :title="selectedObjectName || 'Объект'" @command="handleCommand" />
      </div>
    </div>
    <CanvasContextMenu :visible="contextMenu.visible" :x="contextMenu.x" :y="contextMenu.y" :has-selection="selectedElements.length > 0" :can-paste="false" @command="onContextCommand" />
    <aside class="properties-panel">
      <template v-if="selectedBusbar"><h2>Свойства шины</h2><label>Класс напряжения<select v-model="selectedBusbar.voltageClassId" @change="syncBusbarLabels(selectedBusbar)"><option v-for="item in voltageClassColors" :key="item.id" :value="item.id">{{ item.label }} — {{ item.colorName }}</option></select></label><label>Ячеек<input v-model.number="selectedBusbar.slots" type="number" @change="normalizeBusbarSlots(selectedBusbar)" /></label><label>Шаг<input v-model.number="selectedBusbar.slotSpacing" type="number" @change="normalizeBusbarSlots(selectedBusbar)" /></label><label>Подпись<input v-model="selectedBusbar.label" @change="syncBusbarLabels(selectedBusbar)" /></label><button class="panel-button" @click="addBusbarSlot(selectedBusbar)">+ Ячейка</button><button class="panel-button" @click="removeBusbarSlot(selectedBusbar)">− Ячейка</button></template>
      <template v-else-if="selectedSymbol"><h2>Свойства символа</h2><label>Наименование<input v-model="selectedSymbol.label" /></label><p>Привязка: {{ selectedSymbol.attachedSlotId || 'нет' }}</p></template>
      <template v-else><h2>Свойства</h2><p>Выберите объект. Ctrl+клик — мультивыбор.</p><button class="panel-button" @click="createSampleBusbar()">Добавить шину</button><button class="panel-button" @click="createCircuitBreaker()">Добавить выключатель</button><button class="panel-button" @click="createTextObject()">Добавить текст</button></template>
    </aside>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import CanvasContextMenu from './CanvasContextMenu.vue'
import MiniToolbar from './MiniToolbar.vue'
import { isoPageSizes, normalizeCanvasSettings, type CanvasSettings } from '../../lib/editor/canvasSettings'
import type { EditorCommand, EditorInteractionMode } from '../../lib/editor/interactionModes'
import { rectsIntersect, snapPoint, type Point, type SnapCandidate, type SnapKind } from '../../lib/editor/snapService'
import { voltageClassColors, voltageColorById, voltageKvById, type VoltageClassId } from '../../lib/editor/voltageClasses'

type PrimitiveKind = 'rectangle' | 'ellipse' | 'line'
type TextObject = { id: string; text: string; anchor: Point; center: Point; rotationDeg: number; fontSize: number; fill: string; busbarId?: string }
type Busbar = { id: string; x: number; y: number; width: number; height: number; slots: number; slotSpacing: number; labelStart: number; label: string; voltageKv: number; voltageClassId: VoltageClassId }
type Primitive = { id: string; kind: PrimitiveKind; x: number; y: number; width: number; height: number; stroke: string; fill: string; strokeWidth: number }
type SymbolObject = { id: string; x: number; y: number; width: number; height: number; label: string; voltageClassId: VoltageClassId; attachedSlotId: string | null }
type Slot = { id: string; busbarId: string; x: number; y: number }
type Selected = { kind: 'text' | 'busbar' | 'primitive' | 'symbol'; id: string }
type Rect = { x: number; y: number; width: number; height: number }

const props = defineProps<{ activeMode: EditorInteractionMode; command: EditorCommand | null; settings: CanvasSettings }>()
const emit = defineEmits<{ modeChange: [mode: EditorInteractionMode]; statusChange: [status: { pointer: Point | null; snapKind: SnapKind | null; snapLabel: string; selectedObjectName: string; message: string }]; settingsChange: [settings: CanvasSettings]; commandHandled: [] }>()
const surfaceRef = ref<HTMLDivElement | null>(null)
const viewOrigin = reactive<Point>({ x: -450, y: -260 })
const canvasPixels = reactive({ width: 1000, height: 650 })
const pointerPoint = ref<Point | null>(null)
const selectedElements = ref<Selected[]>([])
const busbars = ref<Busbar[]>([])
const textObjects = ref<TextObject[]>([])
const primitiveObjects = ref<Primitive[]>([])
const symbolObjects = ref<SymbolObject[]>([])
const guides = ref<{ id: string; orientation: 'vertical' | 'horizontal'; position: number }[]>([])
const marqueeRect = ref<Rect | null>(null)
const contextMenu = reactive({ visible: false, x: 0, y: 0, point: { x: 0, y: 0 } as Point })
const message = ref('Редактор готов.')

const viewBoxWidth = computed(() => canvasPixels.width / props.settings.zoom)
const viewBoxHeight = computed(() => canvasPixels.height / props.settings.zoom)
const canvasViewBox = computed(() => `${viewOrigin.x} ${viewOrigin.y} ${viewBoxWidth.value} ${viewBoxHeight.value}`)
const majorGridStep = computed(() => props.settings.gridStep * 5)
const handleSize = computed(() => Math.max(5 / props.settings.zoom, 3))
const pageSize = computed(() => { const base = isoPageSizes[props.settings.pageFormat]; return props.settings.pageOrientation === 'landscape' ? { width: Math.max(base.width, base.height), height: Math.min(base.width, base.height) } : { width: Math.min(base.width, base.height), height: Math.max(base.width, base.height) } })
const pageRect = computed(() => ({ x: -pageSize.value.width / 2, y: -pageSize.value.height / 2, width: pageSize.value.width, height: pageSize.value.height }))
const verticalGuides = computed(() => guides.value.filter((g) => g.orientation === 'vertical'))
const horizontalGuides = computed(() => guides.value.filter((g) => g.orientation === 'horizontal'))
const baySlots = computed<Slot[]>(() => busbars.value.flatMap((b) => Array.from({ length: b.slots }, (_, i) => ({ id: `${b.id}_slot_${i + 1}`, busbarId: b.id, x: b.x + 12 + i * b.slotSpacing, y: b.y + b.height / 2 }))))
const symbolAttachmentLines = computed(() => symbolObjects.value.flatMap((s) => { if (!s.attachedSlotId) return []; const slot = baySlots.value.find((x) => x.id === s.attachedSlotId); if (!slot) return []; const t = bottomTerminal(s); return [{ id: `${s.id}_${slot.id}`, x1: t.x, y1: t.y, x2: slot.x, y2: slot.y, color: voltageColorById(s.voltageClassId) }] }))
const selectedBusbar = computed(() => selectedElements.value.length === 1 && selectedElements.value[0].kind === 'busbar' ? busbars.value.find((x) => x.id === selectedElements.value[0].id) ?? null : null)
const selectedSymbol = computed(() => selectedElements.value.length === 1 && selectedElements.value[0].kind === 'symbol' ? symbolObjects.value.find((x) => x.id === selectedElements.value[0].id) ?? null : null)
const selectedObjectName = computed(() => selectedBusbar.value?.label ?? selectedSymbol.value?.label ?? '')
const snapCandidates = computed<SnapCandidate[]>(() => baySlots.value.map((s) => ({ x: s.x, y: s.y, kind: 'slot', label: s.id })))
const selectionOverlayRect = computed<Rect | null>(() => { const rects = selectedElements.value.map(objectWorldRect).filter((r): r is Rect => Boolean(r)); if (!rects.length) return null; const x = Math.min(...rects.map((r) => r.x)); const y = Math.min(...rects.map((r) => r.y)); const r = Math.max(...rects.map((v) => v.x + v.width)); const b = Math.max(...rects.map((v) => v.y + v.height)); return { x, y, width: r - x, height: b - y } })
const selectionHandles = computed(() => { const r = selectionOverlayRect.value; if (!r) return []; return [{ id: 'nw', x: r.x, y: r.y }, { id: 'ne', x: r.x + r.width, y: r.y }, { id: 'se', x: r.x + r.width, y: r.y + r.height }, { id: 'sw', x: r.x, y: r.y + r.height }] })
const miniToolbarPosition = computed(() => { const r = selectionOverlayRect.value; if (!r) return null; return { x: (r.x + r.width / 2 - viewOrigin.x) * props.settings.zoom, y: (r.y - viewOrigin.y) * props.settings.zoom - 8 } })

function emitStatus(point: Point | null, snapKind: SnapKind | null, snapLabel: string): void { emit('statusChange', { pointer: point, snapKind, snapLabel, selectedObjectName: selectedObjectName.value, message: message.value }) }
function worldPointFromClient(x: number, y: number): Point | null { const rect = surfaceRef.value?.getBoundingClientRect(); if (!rect) return null; return { x: viewOrigin.x + (x - rect.left) / props.settings.zoom, y: viewOrigin.y + (y - rect.top) / props.settings.zoom } }
function snapCanvasPoint(point: Point) { return snapPoint(point, { enabled: props.settings.snapEnabled, gridSize: props.settings.gridStep, snapGrid: props.settings.snapGrid, tolerance: props.settings.snapTolerance, candidates: snapCandidates.value }) }
function onPointerMove(event: PointerEvent): void { const p = worldPointFromClient(event.clientX, event.clientY); if (!p) return; const s = snapCanvasPoint(p); pointerPoint.value = { x: s.x, y: s.y }; emitStatus(pointerPoint.value, s.kind, s.label) }
function onPaletteDrop(event: DragEvent): void { const command = event.dataTransfer?.getData('application/x-electroscheme-command') as EditorCommand | ''; const p = worldPointFromClient(event.clientX, event.clientY); if (!command || !p) return; handleCommandAtPoint(command, snapCanvasPoint(p)) }
function autoBusbarWidth(b: Busbar): number { return 24 + Math.max(0, b.slots - 1) * b.slotSpacing }
function createSampleBusbar(point?: Point): void { const s = snapCanvasPoint(point ?? pointerPoint.value ?? { x: -180, y: -10 }); const b: Busbar = { id: `busbar_${Date.now()}`, x: s.x, y: s.y, width: 0, height: 20, slots: 8, slotSpacing: 48, labelStart: 1, label: '1С 10 кВ', voltageKv: 10, voltageClassId: '10' }; b.width = autoBusbarWidth(b); busbars.value.push(b); ensureBusbarLabels(b); selectSingle('busbar', b.id); emitStatus(s, 'grid', 'Шина') }
function ensureBusbarLabels(b: Busbar): void { textObjects.value = textObjects.value.filter((t) => t.busbarId !== b.id); for (let i = 0; i < b.slots; i += 1) { const x = b.x + 12 + i * b.slotSpacing; const y = b.y - 28; textObjects.value.push({ id: `${b.id}_label_${i + 1}`, text: String(b.labelStart + i), anchor: { x, y }, center: { x, y }, rotationDeg: 0, fontSize: 16, fill: '#111827', busbarId: b.id }) } const x = b.x + b.width + 52; const y = b.y + b.height / 2; textObjects.value.push({ id: `${b.id}_caption`, text: b.label, anchor: { x, y }, center: { x, y }, rotationDeg: 0, fontSize: 18, fill: '#111827', busbarId: b.id }) }
function syncBusbarLabels(b: Busbar | null): void { if (!b) return; b.voltageKv = voltageKvById(b.voltageClassId); b.width = autoBusbarWidth(b); ensureBusbarLabels(b); for (const s of symbolObjects.value) if (s.attachedSlotId?.startsWith(`${b.id}_`)) s.voltageClassId = b.voltageClassId }
function normalizeBusbarSlots(b: Busbar | null): void { if (!b) return; b.slots = Math.max(1, Math.min(40, Math.round(b.slots))); b.slotSpacing = Math.max(8, b.slotSpacing); syncBusbarLabels(b) }
function addBusbarSlot(b: Busbar | null = selectedBusbar.value): void { if (b) { b.slots += 1; normalizeBusbarSlots(b) } }
function removeBusbarSlot(b: Busbar | null = selectedBusbar.value): void { if (b) { b.slots = Math.max(1, b.slots - 1); normalizeBusbarSlots(b) } }
function createCircuitBreaker(point?: Point): void { const s = snapCanvasPoint(point ?? pointerPoint.value ?? { x: 0, y: 0 }); const nearest = findNearestBusbarSlot(s, 70); const obj: SymbolObject = { id: `symbol_${Date.now()}`, x: nearest ? nearest.x - 14 : s.x - 14, y: nearest ? nearest.y - 118 : s.y - 17, width: 28, height: 34, label: `В-${symbolObjects.value.length + 1}`, voltageClassId: nearest ? busbarVoltageClass(nearest.busbarId) : '10', attachedSlotId: nearest?.id ?? null }; symbolObjects.value.push(obj); selectSingle('symbol', obj.id); emitStatus(s, nearest ? 'slot' : s.kind, nearest?.id ?? s.label) }
function createTextObject(point?: Point): void { const s = snapCanvasPoint(point ?? pointerPoint.value ?? { x: 0, y: 0 }); const id = `text_${Date.now()}`; textObjects.value.push({ id, text: 'Текст', anchor: { x: s.x, y: s.y }, center: { x: s.x, y: s.y }, rotationDeg: 0, fontSize: 16, fill: '#111827' }); selectSingle('text', id) }
function createPrimitive(kind: PrimitiveKind, point?: Point): void { const s = snapCanvasPoint(point ?? pointerPoint.value ?? { x: 0, y: 0 }); const id = `primitive_${Date.now()}`; primitiveObjects.value.push({ id, kind, x: s.x, y: s.y, width: kind === 'line' ? 80 : 90, height: kind === 'line' ? 0 : 45, stroke: '#111827', fill: kind === 'line' ? 'none' : '#ffffff', strokeWidth: 1.2 }); selectSingle('primitive', id) }
function busbarVoltageClass(id: string): VoltageClassId { return busbars.value.find((b) => b.id === id)?.voltageClassId ?? '10' }
function bottomTerminal(s: SymbolObject): Point { return { x: s.x + s.width / 2, y: s.y + s.height + 24 } }
function findNearestBusbarSlot(point: Point, tolerance: number) { let best: Slot | null = null; let bestDistance = Infinity; for (const slot of baySlots.value) { const d = Math.hypot(point.x - slot.x, point.y - slot.y); if (d < bestDistance && d <= tolerance) { best = slot; bestDistance = d } } return best }
function attachSymbolToNearestSlot(s: SymbolObject, tolerance: number): void { const nearest = findNearestBusbarSlot(bottomTerminal(s), tolerance); s.attachedSlotId = nearest?.id ?? null; if (nearest) s.voltageClassId = busbarVoltageClass(nearest.busbarId) }
function handleCommand(c: EditorCommand): void { handleCommandAtPoint(c, pointerPoint.value ?? contextMenu.point); emit('commandHandled') }
function handleCommandAtPoint(c: EditorCommand, p: Point): void { if (c === 'create_sample_busbar') createSampleBusbar(p); else if (c === 'create_circuit_breaker') createCircuitBreaker(p); else if (c === 'create_text') createTextObject(p); else if (c === 'create_rectangle') createPrimitive('rectangle', p); else if (c === 'create_ellipse') createPrimitive('ellipse', p); else if (c === 'create_line') createPrimitive('line', p); else if (c === 'delete') deleteSelected() }
function selectSingle(kind: Selected['kind'], id: string): void { selectedElements.value = [{ kind, id }] }
function onBusbarPointerDown(e: PointerEvent, id: string): void { selectSingle('busbar', id); startDrag(e) }
function onSymbolPointerDown(e: PointerEvent, id: string): void { selectSingle('symbol', id); startDrag(e) }
function onPrimitivePointerDown(e: PointerEvent, id: string): void { selectSingle('primitive', id); startDrag(e) }
function onTextPointerDown(e: PointerEvent, id: string): void { selectSingle('text', id); startDrag(e) }
function startDrag(e: PointerEvent): void { const start = worldPointFromClient(e.clientX, e.clientY); if (!start) return; const selected = [...selectedElements.value]; const baselines = selected.map((x) => ({ item: x, rect: objectWorldRect(x) })).filter((x) => x.rect) as { item: Selected; rect: Rect }[]; const move = (ev: PointerEvent) => { const p = worldPointFromClient(ev.clientX, ev.clientY); if (!p) return; const s = snapCanvasPoint(p); const dx = s.x - start.x; const dy = s.y - start.y; for (const base of baselines) moveObject(base.item, base.rect, dx, dy) }; const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up) }
function moveObject(item: Selected, r: Rect, dx: number, dy: number): void { if (item.kind === 'busbar') { const b = busbars.value.find((x) => x.id === item.id); if (!b) return; b.x = r.x + dx; b.y = r.y + dy; ensureBusbarLabels(b) } else if (item.kind === 'symbol') { const s = symbolObjects.value.find((x) => x.id === item.id); if (!s) return; s.x = r.x + dx; s.y = r.y + 24 + dy; attachSymbolToNearestSlot(s, 48) } else if (item.kind === 'primitive') { const p = primitiveObjects.value.find((x) => x.id === item.id); if (!p) return; p.x = r.x + dx; p.y = r.y + dy } else { const t = textObjects.value.find((x) => x.id === item.id); if (!t) return; t.anchor = { x: r.x + 25 + dx, y: r.y + 12 + dy }; t.center = { ...t.anchor } } }
function onCanvasPointerDown(e: PointerEvent): void { const p = worldPointFromClient(e.clientX, e.clientY); if (!p) return; if (!e.ctrlKey) selectedElements.value = []; startMarquee(e, p) }
function startMarquee(e: PointerEvent, start: Point): void { const move = (ev: PointerEvent) => { const p = worldPointFromClient(ev.clientX, ev.clientY); if (!p) return; marqueeRect.value = { x: Math.min(start.x, p.x), y: Math.min(start.y, p.y), width: Math.abs(p.x - start.x), height: Math.abs(p.y - start.y) } }; const up = () => { if (marqueeRect.value && marqueeRect.value.width > 2 && marqueeRect.value.height > 2) selectedElements.value = allSelectable().filter((x) => { const r = objectWorldRect(x); return r ? rectsIntersect(marqueeRect.value as Rect, r) : false }); marqueeRect.value = null; window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up) }
function allSelectable(): Selected[] { return [...busbars.value.map((x) => ({ kind: 'busbar' as const, id: x.id })), ...textObjects.value.map((x) => ({ kind: 'text' as const, id: x.id })), ...primitiveObjects.value.map((x) => ({ kind: 'primitive' as const, id: x.id })), ...symbolObjects.value.map((x) => ({ kind: 'symbol' as const, id: x.id }))] }
function objectWorldRect(s: Selected): Rect | null { if (s.kind === 'busbar') { const b = busbars.value.find((x) => x.id === s.id); return b ? { x: b.x, y: b.y, width: b.width, height: b.height } : null } if (s.kind === 'symbol') { const o = symbolObjects.value.find((x) => x.id === s.id); return o ? { x: o.x, y: o.y - 24, width: o.width, height: o.height + 48 } : null } if (s.kind === 'primitive') { const p = primitiveObjects.value.find((x) => x.id === s.id); return p ? { x: p.x, y: p.y, width: p.width, height: p.height || 1 } : null } const t = textObjects.value.find((x) => x.id === s.id); return t ? { x: t.center.x - 25, y: t.center.y - 12, width: 50, height: 24 } : null }
function deleteSelected(): void { for (const s of selectedElements.value) { if (s.kind === 'busbar') { busbars.value = busbars.value.filter((x) => x.id !== s.id); textObjects.value = textObjects.value.filter((x) => x.busbarId !== s.id) } else if (s.kind === 'symbol') symbolObjects.value = symbolObjects.value.filter((x) => x.id !== s.id); else if (s.kind === 'primitive') primitiveObjects.value = primitiveObjects.value.filter((x) => x.id !== s.id); else textObjects.value = textObjects.value.filter((x) => x.id !== s.id) } selectedElements.value = [] }
function onWheelZoom(e: WheelEvent): void { emit('settingsChange', normalizeCanvasSettings({ ...props.settings, zoom: Math.min(Math.max(props.settings.zoom * (e.deltaY < 0 ? 1.08 : 0.92), 0.2), 6) })) }
function onContextMenu(e: MouseEvent): void { const p = worldPointFromClient(e.clientX, e.clientY); contextMenu.visible = true; contextMenu.x = e.clientX; contextMenu.y = e.clientY; contextMenu.point = p ?? { x: 0, y: 0 } }
function onContextCommand(c: EditorCommand): void { hideContextMenu(); handleCommandAtPoint(c, contextMenu.point) }
function hideContextMenu(): void { contextMenu.visible = false }
watch(() => props.command, (c) => { if (c) handleCommand(c) })
</script>
<style scoped>
.canvas-workspace{position:relative;display:grid;grid-template-columns:1fr 280px;min-height:0;height:100%;background:#e5edf7;overflow:hidden}.canvas-frame{display:grid;grid-template-columns:32px 1fr;grid-template-rows:28px 1fr;min-width:0;min-height:0;overflow:hidden}.ruler-corner{display:grid;place-items:center;border-right:1px solid #cbd5e1;border-bottom:1px solid #cbd5e1;background:#f8fafc;color:#64748b;font-size:10px;font-weight:800}.top-ruler,.left-ruler{background:#f8fafc;color:#64748b;font-size:11px}.top-ruler{height:28px;border-bottom:1px solid #cbd5e1;padding-left:10px;line-height:28px}.left-ruler{border-right:1px solid #cbd5e1;writing-mode:vertical-rl;text-align:center}.canvas-surface{position:relative;min-width:0;min-height:0;overflow:hidden;background:#dedbe0}.editor-canvas{width:100%;height:100%;min-width:900px;min-height:520px;display:block;background:#dedbe0;cursor:crosshair}.iso-page-fill{fill:#fff}.iso-page-outline{fill:none;stroke:#8797ad;stroke-width:.7;vector-effect:non-scaling-stroke}.iso-page-label{fill:#64748b;font-family:Arial,sans-serif;font-size:9px}.origin-line{stroke:#ef4444;stroke-width:.45;opacity:.42;stroke-dasharray:2 2;vector-effect:non-scaling-stroke}.origin-dot{fill:#ef4444;opacity:.44}.origin-label{fill:#ef4444;font-size:6px;font-family:Arial,sans-serif;opacity:.55}.busbar-object,.primitive-object,.symbol-object{cursor:move}.busbar{stroke:#111827;stroke-width:.8;vector-effect:non-scaling-stroke}.bay-slot,.symbol-terminal{fill:#fff;stroke:#111827;stroke-width:1.2;vector-effect:non-scaling-stroke}.symbol-body,.symbol-line,.electrical-connection{stroke-width:1.4;vector-effect:non-scaling-stroke}.symbol-label{fill:#111827;font-family:Arial,sans-serif;font-size:14px;dominant-baseline:middle}.canvas-text{font-family:Arial,sans-serif;cursor:grab;user-select:none}.user-guide-line{stroke:#0ea5e9;stroke-width:.8;stroke-dasharray:5 4}.selection-outline{fill:none;stroke:#2563eb;stroke-width:.9;stroke-dasharray:3 2;vector-effect:non-scaling-stroke}.selection-handle{fill:#fff;stroke:#2563eb;stroke-width:.8;vector-effect:non-scaling-stroke}.selection-marquee{fill:rgba(37,99,235,.08);stroke:#2563eb;stroke-width:.8;stroke-dasharray:3 3;vector-effect:non-scaling-stroke}.empty-canvas-hint{fill:#64748b;font-family:Arial,sans-serif;font-size:22px}.empty-canvas-hint .hint-small{fill:#94a3b8;font-size:13px}.properties-panel{border-left:1px solid #cbd5e1;background:#f8fafc;padding:12px;overflow:hidden}.properties-panel h2{margin:0 0 10px;font-size:14px}.properties-panel label{display:grid;gap:4px;margin-bottom:8px;color:#475569;font-size:12px;font-weight:800}.properties-panel input,.properties-panel select{border:1px solid #cbd5e1;border-radius:8px;padding:6px 8px;background:white}.properties-panel p{color:#475569;font-size:12px;line-height:1.4}.panel-button{display:block;width:100%;margin-bottom:8px;border:1px solid #bfdbfe;border-radius:8px;background:white;color:#1e3a8a;cursor:pointer;font-weight:800;padding:8px 10px}
</style>
